<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('adminhtml')->__('Slideshow Manager') ?>
                </h3>
            </td>
            <td class="a-right">
                <?php echo $this->getAddNewButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<template id="stuntcoders-add-photo">
    <input id="image" name="image[]" value="" type="file" class="input-file" multiple>
</template>
<div>
    <div class="entry-edit">
        <form id="stuntcoders_slideshow"
              name="stuntcoders_slideshow"
              action="<?php echo $this->getUrl('*/*/save'); ?>"
              method="post"
              enctype="multipart/form-data">
            <div>
                <input name="form_key" type="hidden" value="<? echo $this->getFormKey(); ?>">
            </div>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">
                    <?php echo Mage::helper('adminhtml')->__('Slideshow Information') ?>
                </h4>
                <div class="form-buttons"></div>
            </div>
            <div class="fieldset" id="stuntcoders_form">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                        <tr>
                            <td class="label">
                                <label for="code"><?php echo Mage::helper('adminhtml')->__('Code') ?></label>
                            </td>
                            <td class="value">
                                <input id="code" name="code" value="" type="text" class=" input-text">
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label for="name"><?php echo Mage::helper('adminhtml')->__('Name') ?></label>
                            </td>
                            <td class="value">
                                <input id="name" name="name" value="" type="text" class=" input-text">
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label for="status"><?php echo Mage::helper('adminhtml')->__('Status') ?></label>
                            </td>
                            <td class="value">
                                <select id="status" name="status">
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label for="jsonObject">
                                    <?php echo Mage::helper('adminhtml')->__('Json Object') ?>
                                </label>
                            </td>
                            <td class="value">
                                <textarea id="jsonObject" name="jsonObject" cols="30" rows="4"></textarea>
                            </td>
                        </tr>
                        <tr class="stuntcoders-add-photo">
                            <td class="label">
                                <label for="image"><?php echo Mage::helper('adminhtml')->__('Images') ?></label>
                            </td>
                            <td class="imageValue">
                                <input id="image" name="image[]" value="" type="file" class="input-file" multiple>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <button class="add-more-photos">
                        <?php echo Mage::helper('adminhtml')->__('Add more photos') ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    var stuntcoders_slideshow = new varienForm('form');
    jQuery('.add-more-photos').click(function(e){
        e.preventDefault();
        jQuery('#stuntcoders_form')
            .find('.stuntcoders-add-photo')
            .find('.imageValue')
            .append(jQuery(('#stuntcoders-add-photo')).html());;
    });
</script>
