<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-blog"><?php echo Mage::helper('adminhtml')->__('Banner Manager') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getFormHtml() ?>
</div>
<script type="text/javascript">
    var stuntcoders_slideshow = new varienForm('stuntcoders_slideshow');
</script>