<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-blog"><?php echo Mage::helper('adminhtml')->__('Banner Slideshow') ?></h3>
            </td>
            <td class="a-right">
                <?php echo $this->getAddNewButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('slideshow.grid'); ?>
</div>
