<?php if ($this->isEnabled()): ?>
    <div class="flexslider">
      <ul class="slides">
            <?php
            foreach ($this->getImages() as $image) {
                if ($image['is_enabled']) {
                    echo "<li>";
                    echo "<img src='{$this->getImagePath($image)}'/>";
                    echo "</li>";
                }
            }
            ?>
      </ul>
    </div>
    <script type="text/javascript">
    jQuery(window).load(function() {
        jQuery('.flexslider').flexslider(<?php echo $this->getSliderJson(); ?>);
    });
    </script>
<?php endif; ?>
